### ISSUE TITLE
Add D in action chapter

### ISSUE THREAD

**Issue by wilzbach** [dlang-tour/english#194]
As there are many great examples about D's features, which don't fit on a page or dlang.org, a good idea would be to add them as final chapter to the tour for interested people who want to browse "real world examples".
A first lists of such examples that don't fit anywhere yet:

https://github.com/dlang/dlang.org/pull/1762
http://forum.dlang.org/post/cxzmdrueeuxweqlmtdkm@forum.dlang.org

**Comment by EmTee70** [comment]
I like this idea very much.
But there should be an very detailed comments explaining what is done with which command from which import. The coolest thing would be to link the code comments directly with the phobos/runtime docs.

The answers to my question about a ruby  like n.times{} are nice, too:

The link is to the forum view at digitalmars, because it was easier to find (first google match):

http://www.digitalmars.com/d/archives/digitalmars/D/learn/Most_convenient_way_to_write_a_loop_with_fixed_length_and_no_need_for_94052.html

```
import std.stdio;
auto times(alias Func, T)(T number) {
     import std.range : iota;
     import std.algorithm : each;
     return number.iota.each!(_ => Func());
}

void foo() {
     writeln("foo");
}

void bar() {
     writeln("bar");
}

void main() {
     3.times!({ foo(); bar(); });
}
```
 from Ali

Or alternatively:
```void times(alias fun)(size_t i) {
	foreach(unused;0..i)
		fun();
}
```
you can write your own function. It is simple.

```
void times(alias fun)(size_t i) {
	foreach(unused;0..i)
		fun();
}
```
and use it like this:
```
10.times!({ writeln("yaaay"); });
```
from Anton Fediushin

**Comment by wilzbach** [comment]
First example is there: https://github.com/dlang-tour/english/pull/217

**Comment by wilzbach** [comment]
Hence, I'm closing this issue.
The example should appear shortly at https://tour.dlang.org/tour/en/byexample/code-generation-parser

@ other / future readers: please feel more than free to add further interesting examples showing modern D usage.
